import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { cn } from "../../lib/utils";
import { getThemeDataFromCookies } from "@/components/ui/ThemePicker";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const search = new URLSearchParams(getThemeDataFromCookies());

  const style = await fetch(
    process.env.NEXT_PUBLIC_HOST + "/api/my-theme?" + search.toString()
  ).then((data) => data.json());

  return (
    <html className="h-full" lang="en" style={style.style}>
      <body
        className={cn(
          "min-h-screen bg-accent-900/50 font-sans antialiased flex items-center justify-center",
          inter
        )}
      >
        {children}
      </body>
    </html>
  );
}
